apiVersion: v1
kind: Service
metadata:
  name: rs-userservice
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: https
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: rs-userservice
  type: NodePort